name = input("Enter your name:")
hobby = input("What is your hobby?")
fav_number = int(input("What is your favorite number?"))
fav_color = input("what's your favorite color?")
print("Friend's name:" + name)
print("Hobby:" + hobby)
print("Favorite Number:" + str(fav_number))
print("Favorite Color:" + fav_color)
